export const Messages = {
  USER_ARRAY_EMPTY: "Empty request body",
  NAME_REQUIRED: `Field 'name' wajib diisi`,
  NISN_REQUIRED: `Field 'nisn' wajib diisi`,
  NOMOR_INDUK_REQUIRED: `Field 'nomor_induk' wajib diisi`,
  NIP_REQUIRED: `Field 'nip' wajib diisi`,
  KELASID_REQUIRED: ` Field 'kelas' wajib diisi`,
  PASSWORD_REQUIRED: `Field 'password' wajib diisi`,
  INTERNAL_ERROR: "Error creating users",
  WRONG_PASSWORD: "password salah",
  USER_NOT_FOUND: "Pengguna tidak ditemukan",
  SERVER_ERROR: "Terjadi kesalahan server",
  LOGIN_SUCCESS: "Login berhasil",
  LOGOUT_SUCCESS: "Logout berhasil",
  ACCOUNT_LOCKED: "Coba 3 Menit Lagi",
  PASSWORD_TOO_SHORT: "Password kurang dari 6 karakter",
  PELANGGARAN_ID_REQUIRED: `Field 'pelanggaranId' wajib diisi`,
  PELANGGARAN_REQUIRED: `Field 'pelanggaran' wajib diisi`,
  POIN_PELANGGARAN_REQUIRED: `Field 'poin' wajib diisi`,
  ID_PELANGGAR_REQUIRED: `Field 'idPelanggar' wajib diisi`,
  ID_KELAS_PELANGGAR_REQUIRED: `Field 'idKelasPelanggar' wajib diisi`,
  ID_PENCATAT_REQUIRED: `Field 'idPencatat' wajib diisi`,
  BUKTI_PELANGGARAN_REQUIRED: `Field 'bukti' wajib diisi`,
  SEMESTER_PELANGGARAN_REQUIRED: `Field 'semester' wajib diisi`,
  TIME_PELANGGARAN_REQUIRED: `Field 'time' wajib diisi`,
};